apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - service.yml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: public-gateway-certificates
  files:
    - configs/certificates/localhost.key
    - configs/certificates/localhost.crt

configMapGenerator:
  - name: public-gateway-configmap
    files:
      - configs/nginx.conf
      - configs/credentials
      - promtail-config.yml
 