apiVersion: v1
kind: Service
metadata:
  name: public-gateway
spec:
  selector:
    app: public-gateway
  ports:
  - name: http
    port: 8080
    targetPort: 80
    nodePort: 30080
  - name: https
    port: 8443
    targetPort: 443
    nodePort: 30443
  type: NodePort
