trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build api.client.subscriptions
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/microservices/api.client.subscriptions/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Build api.core.subscriptions
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/microservices/api.core.subscriptions/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Build api.core.mail
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/microservices/api.core.mail/Dockerfile'
        tags: |
          $(tag)