trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.SourceVersion)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: build_client_subscriptions
    displayName: Build api-client-subscriptions
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Docker build & push
      inputs:
        command: buildAndPush
        containerRegistry: 'Docker Hub (jsoliveira)'
        repository: 'jsoliveira/api-client-subscriptions'
        dockerfile: '$(Build.SourcesDirectory)/apis/api-client-subscriptions/Dockerfile'
        tags: |
          $(tag)

  - job: build_api_core_subscriptions
    displayName: Build api-core-subscriptions
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build api-core-subscriptions
      inputs:
        command: buildAndPush
        containerRegistry: 'Docker Hub (jsoliveira)'
        repository: 'jsoliveira/api-core-subscriptions'
        dockerfile: '$(Build.SourcesDirectory)/apis/api-core-subscriptions/Dockerfile'
        tags: |
          $(tag)

  - job: build_api_core_mail
    displayName: Build api-core-mail
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build api-core-mail
      inputs:
        command: buildAndPush
        repository: 'jsoliveira/api-core-mail'
        containerRegistry: 'Docker Hub (jsoliveira)'
        dockerfile: '$(Build.SourcesDirectory)/apis/api-core-mail/Dockerfile'
        tags: |
          $(tag)
  - job: build_public_gateway
    displayName: Build public-gateway
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build public-gateway
      inputs:
        command: buildAndPush
        repository: 'jsoliveira/public-gateway'
        containerRegistry: 'Docker Hub (jsoliveira)'
        dockerfile: '$(Build.SourcesDirectory)/services/gateways/public/Dockerfile'
        tags: |
          $(tag)
  - job: build_private_gateway
    displayName: Build private-gateway
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build private-gateway
      inputs:
        command: buildAndPush
        repository: 'jsoliveira/private-gateway'
        containerRegistry: 'Docker Hub (jsoliveira)'
        dockerfile: '$(Build.SourcesDirectory)/services/gateways/private/Dockerfile'
        tags: |
          $(tag)

  