
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - service.yml

configMapGenerator:
  - name: grafana-configmap
    files:
      - configs/dashboards.yml
      - configs/datasources.yml
  - name: grafana-dashboards-configmap
    files:
      - configs/dashboards/default.json
  