apiVersion: apps/v1
kind: Deployment
metadata:
  name: smtp
spec:
  selector:
    matchLabels:
      app: smtp
  template:
    metadata:
      labels:
        app: smtp
    spec:
      containers:
      - name: smtp
        image: rnwood/smtp4dev:v3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 80
        - name: service
          containerPort: 25
