apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-core-mail
spec:
  selector:
    matchLabels:
      app: api-core-mail
  template:
    metadata:
      labels:
        app: api-core-mail
    spec:
      containers:
      - name: api-core-mail
        image: jsoliveira/api-core-mail:4670300e1ca637776509c1a96e238b9a935d9d55
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
