apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-core-mail
spec:
  selector:
    matchLabels:
      app: api-core-mail
  template:
    metadata:
      labels:
        app: api-core-mail
    spec:
      containers:
      - name: api-core-mail
        image: jsoliveira/api-core-mail:latest
        imagePullPolicy: Always
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: K8s
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
