apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc
spec:
  storageClassName: "manual"
  volumeName: loki-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi