apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image:  prom/prometheus:v2.23.0
        volumeMounts:
          - mountPath: /etc/prometheus/prometheus.yml
            name: prometheus-configmap
            subPath: prometheus.yml
          - mountPath: /prometheus/data
            name: prometheus-data

        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 9090
      volumes:
        - name: prometheus-configmap
          configMap:
            name: prometheus-configmap
        - name: prometheus-data
          hostPath:
            type: DirectoryOrCreate
            path: "/run/desktop/mnt/host/c/tmp/prometheus"
