apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - service.yml
  - persistentvolumeclaim.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: prometheus-configmap
    files:
      - configs/prometheus.yml