apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
spec:
  storageClassName: manual
  volumeName: prometheus-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi