apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - statefulset.yml
  - service.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: rabbitmq-cluster-configmap
    files:
      - configs/rabbitmq.conf
      - configs/enabled_plugins