apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
  - name: http
    port: 5672
    targetPort: 5672
  - name: service
    port: 15672
    targetPort: 15672