apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  replicas: 2
  serviceName: rabbitmq
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:        
        - name: rabbitmq
          image: rabbitmq:3-management
          env:
            - name: RABBITMQ_ERLANG_COOKIE
              value: DSHEVCXBBETJJVJWTOWT
            - name: RABBITMQ_USE_LONGNAME
              value: 'true'
          volumeMounts:
            - name: rabbitmq-cluster-configmap
              mountPath: "/etc/rabbitmq/rabbitmq.conf"
              subPath: rabbitmq.conf
              readOnly: true
            - name: rabbitmq-cluster-configmap
              mountPath: "/etc/rabbitmq/enabled_plugins"
              subPath: enabled_plugins
              readOnly: true
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"
          ports:
          - name: http
            containerPort: 15672
          - name: service
            containerPort: 5672
          readinessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 60
            periodSeconds: 10   
      volumes:
        - name: rabbitmq-cluster-configmap
          configMap:
            name: rabbitmq-cluster-configmap