apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
- name: Prometheus
  type: prometheus
  url: https://prometheus:9090
  version: 1
  editable: true
- name: Loki
  type: loki
  url: http://loki:3100
  version: 1
  editable: true