apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-core-subscriptions
spec:
  selector:
    matchLabels:
      app: api-core-subscriptions
  template:
    metadata:
      labels:
        app: api-core-subscriptions
    spec:
      containers:
      - name: api-core-subscriptions
        image: jsoliveira/api-core-subscriptions:4670300e1ca637776509c1a96e238b9a935d9d55
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
