version: "3.8"
services:
  # services
  api-client-subscriptions:
    extends:
      file: services.yml
      service: api-client-subscriptions
  api-core-subscriptions:
    extends:
      file: services.yml
      service: api-core-subscriptions
  api-core-mail:
   extends:
      file: services.yml
      service: api-core-mail
  rabbitmq:
    depends_on:
      - rabbit-1
      - rabbit-2
    extends:
      file: services.yml
      service: rabbitmq-lb
  rabbit-1:
    hostname: rabbit-1
    extends:
      file: services.yml
      service: rabbit-node
  rabbit-2:
    hostname: rabbit-2
    extends:
      file: services.yml
      service: rabbit-node

  # gateways 
  public-gateway:
    extends:
      file: gateways.yml
      service: public-gateway
  private-gateway:
    extends:
      file: gateways.yml
      service: private-gateway

  # tools 
  seq:
    extends:
      file: tools.yml
      service: seq
  smtp:
    extends:
      file: tools.yml
      service: smtp
  grafana:
    extends:
      file: tools.yml
      service: grafana
  prometheus:
    extends:
      file: tools.yml
      service: prometheus
  promtail:
    extends:
      file: tools.yml
      service: promtail
  loki:
    extends:
      file: tools.yml
      service: loki
#infrastructure
volumes:
  logs: {}
networks:
  public:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
  private:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24