version: "3.8"
services:
  proxy-gateway:
    image: nginx:alpine
    volumes:
      - ../services/gateways/nginx/certs:/etc/nginx/certs
      - ../services/gateways/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
      - 8443:443
    networks:
      - services
      - public
      - tools
  api.client.subscriptions:
    build: ../../microservices/api.client.subscriptions/
    networks:
      - public
      - private
  api.core.subscriptions:
    build: ../../microservices/api.core.subscriptions/
    networks:
      - private
  api.core.mail:
    build: ../../microservices/api.core.mail/
    networks:
      - private
  rabbit-1: &rabbit
    image: rabbitmq:3-management
    hostname: rabbit-1
    environment:
      RABBITMQ_ERLANG_COOKIE: DSHEVCXBBETJJVJWTOWT
    volumes:
      - ./rabbitmq/:/var/lib/rabbitmq
      - ../services/rabbitmq/etc/:/etc/rabbitmq/
    networks:
      - services
      - private
  rabbit-2:
    <<: *rabbit
    hostname: rabbit-2
  seq:
    image: datalust/seq
    environment:
      ACCEPT_EULA: Y
    ports:
      - 5342:5341
    volumes:
      - ./temp/seq/data:/data
    networks:
      - tools
      - private
  mail:
    image: rnwood/smtp4dev:v3
    networks:
      - tools
      - private
networks:
  public:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
  tools:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
  services:
    driver: bridge
    ipam:
      config:
        - subnet: 192.200.10.0/24
  private:
    driver: bridge 
    ipam:
      config:
        - subnet: 192.100.11.0/24  
