version: "3.8"
services:
  public-gateway:
    build: ../../services/gateways/public/
    restart: on-failure
    ports:
      - '8080:80'
      - '8443:443'
    networks:
      - public
  api.client.subscriptions:
    build: ../../apis/api.client.subscriptions/
    environment:
        ASPNETCORE_ENVIRONMENT: K8s
    networks:
      - public
  private-gateway:
    build: ../../services/gateways/private/
    restart: on-failure
    networks:
      - public
      - private 
  api.core.subscriptions:
    build: ../../apis/api.core.subscriptions/
    environment:
        ASPNETCORE_ENVIRONMENT: K8s
    networks:
      - private
  api.core.mail:
    build: ../../apis/api.core.mail/
    environment:
        ASPNETCORE_ENVIRONMENT: K8s
    networks:
      - private
  rabbitmq:
    image: nginx:alpine
    volumes:
      - ../../services/rabbitmq/lb/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - private
  rabbit-1: &rabbit
    image: rabbitmq:3-management
    hostname: rabbit-1
    environment:
      RABBITMQ_ERLANG_COOKIE: DSHEVCXBBETJJVJWTOWT
    volumes:
      - ./temp/rabbitmq/:/var/lib/rabbitmq
      - ../services/rabbitmq/etc/:/etc/rabbitmq/
    networks:
      - private
  rabbit-2:
    <<: *rabbit
    hostname: rabbit-2 
  seq:
    image: datalust/seq
    environment:
      ACCEPT_EULA: 'Y'
    ports:
      - '5341:5341'
    volumes:
      - ./temp/seq/data:/data
    networks:
      - private
  smtp:
    image: rnwood/smtp4dev:v3
    ports:
      - '2525:25'
    networks:
      - private
networks:
  public:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
  private:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24