version: "3.8"
services:
  
  # public gateway
  public-gateway:
    image: nginx:alpine
    restart: on-failure
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - logs:/var/log/
      - ../../services/gateways/public/certificates:/etc/nginx/certificates
      - ../../services/gateways/public/credentials:/etc/nginx/credentials
      - ../../services/gateways/public/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - public
  #private-gateway
  private-gateway:
    image: nginx:alpine
    restart: on-failure
    volumes:
      - logs:/var/log/
      - ../../services/gateways/private/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - public
      - private 