version: "3.8"
services:

  # public subscriptions api
  api-client-subscriptions:
    build: ../../apis/api-client-subscriptions/
    environment:
        ASPNETCORE_ENVIRONMENT: Docker
    networks:
      - public

  # core subscriptions api
  api-core-subscriptions:
    build: ../../apis/api-core-subscriptions/
    environment:
        ASPNETCORE_ENVIRONMENT: Docker
    networks:
      - private

  # core mail api
  api-core-mail:
    build: ../../apis/api-core-mail/
    environment:
        ASPNETCORE_ENVIRONMENT: Docker
    networks:
      - private

  #rabbitmq load balancer service
  rabbitmq-lb:
    image: nginx:alpine
    restart: on-failure
    volumes:
      - ../../services/rabbitmq/lb/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - private

  #rabbitmq node
  rabbit-node:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: DSHEVCXBBETJJVJWTOWT
    volumes:
      - ./temp/rabbitmq/:/var/lib/rabbitmq
      - ../../services/rabbitmq/etc/:/etc/rabbitmq/
    networks:
      - private