version: "3.8"
services:
  seq:
    image: datalust/seq
    environment:
      ACCEPT_EULA: 'Y'
    ports:
      - '5341:5341'
    volumes:
      - ./temp/seq/data:/data
    networks:
      - private
  smtp:
    image: rnwood/smtp4dev:v3
    ports:
      - '2525:25'
    networks:
      - private