apiVersion: v1
kind: PersistentVolume
metadata:
  name: logging-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/c/tmp"