apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-gateway
spec:
  selector:
    matchLabels:
      app: private-gateway
  template:
    metadata:
      labels:
        app: private-gateway
    spec:
      containers:
      - name: private-gateway
        image: nginx:alpine
        imagePullPolicy: Always
        volumeMounts:
          - name: private-gateway-configmap
            mountPath: "/etc/nginx/nginx.conf"
            subPath: nginx.conf
            readOnly: true
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
      volumes:
        - name: private-gateway-configmap
          configMap:
            name: private-gateway-configmap
