apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-gateway
spec:
  selector:
    matchLabels:
      app: private-gateway
  template:
    metadata:
      labels:
        app: private-gateway
    spec:
      containers:
      - name: promtail
        image:  grafana/promtail:1.6.1
        volumeMounts:
            - mountPath: /etc/promtail/config.yml
              name: private-gateway-configmap
              subPath: promtail-config.yml
            - name: logs
              mountPath: /var/log/nginx/
              readOnly: true
        resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
      - name: private-gateway
        image: nginx:alpine
        imagePullPolicy: Always
        volumeMounts:
          - name: private-gateway-configmap
            mountPath: "/etc/nginx/nginx.conf"
            subPath: nginx.conf
            readOnly: true
          - name: logs
            mountPath: /var/log/nginx/
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
      volumes:
        - name: private-gateway-configmap
          configMap:
            name: private-gateway-configmap
        - name: logs
          emptyDir: {}

