apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-gateway
spec:
  selector:
    matchLabels:
      app: private-gateway
  template:
    metadata:
      labels:
        app: private-gateway
    spec:
      containers:
      - name: private-gateway
        image: jsoliveira/private-gateway:4670300e1ca637776509c1a96e238b9a935d9d55
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
