apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - service.yml

generatorOptions:
  disableNameSuffixHash: true
  
configMapGenerator:
  - name: private-gateway-configmap
    files:
      - configs/nginx.conf
      - promtail-config.yml