apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce  
  hostPath:
    type: DirectoryOrCreate
    path: "/run/desktop/mnt/host/c/tmp/grafana"