apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-client-subscriptions
spec:
  selector:
    matchLabels:
      app: api-client-subscriptions
  template:
    metadata:
      labels:
        app: api-client-subscriptions
    spec:      
      containers:
      - name: api-client-subscriptions
        image: jsoliveira/api-client-subscriptions:4670300e1ca637776509c1a96e238b9a935d9d55
        env:
          - name: Api__CoreSubscriptions__BaseAddress
            value: http://private-gateway.gateways/core.subscriptions/api/v1/Subscription
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
