apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-mq
spec:
  selector:
    matchLabels:
      app: rabbit-mq
  template:
    metadata:
      labels:
        app: rabbit-mq
    spec:
      containers:
      - name: rabbit-mq
        image: rabbitmq:3-management
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: service
          containerPort: 5672
        - name: http
          containerPort: 15672
